#!/bin/sh
(
	prev=$1
	shift
	echo z.$prev.first:
	echo	'	@echo 1 >$@'

	for i
	do
		if [ "$prev" = "contents" ]; then
			echo "z.$i.first: z.contents.first"
			echo '	@echo 2+$$(cat z.contents.first) | bc >$@'
		else
			echo "z.$i.first: $prev.dit"
			echo '	@echo 1+$$(cat z.'$prev'.last) | bc >$@'
		fi
		prev=$i
	done	
)>z.pageorder
echo z.pageorder
