#!/bin/sh

for i
do
	num=$(egrep '^\.(chapter|appendix) ' $i | sed 1q | awk '{print $2}')
	case "$num" in
	CH:* | APP:*)
		num=$(awk '$1==".ds" && $2=="'"$num"'" {print $3}' book.mac)
		;;
	esac
	prefix=$(echo $i | sed 's/\.t$//')
	grep '^\.figure ' $i | awk '{printf(".ds fig:'$prefix':%s \"'$num'-%d\n", $2, NR)}'
done
