#!/bin/sh

export GS_FONTPATH=font
export TROFFONTS=font

chap=$1
p=$(cat z.$chap.first | bc)

grep '^\.ds fig:'$chap':' z.fignums | sed 's/ds fig:'$chap':/ds fig:/' >z.figs
grep '^\.figure ' $chap.t | awk '{system("./runfig '$chap' " $2 " fig/" $2 ".t")}'

$UCB/tbl $chap.t |
	$UCB/troff -mpictures -rp$p book.mac z.fignums z.figs - |
	./twopage |
	./savelast $chap |
	./figures >$chap.dit
